version: '2.1'
services:
  imgart-api:
    build: .
    ports:
      - "4005:4005"
    environment:
      - REDIS_URL=redis://redis-db:6379/0
      - MONGO_URL=mongo-db:27017
    command: ["gin", "-d", "/go/src/github.com/talento90/imgart/cmd/imgartapi/", "-p", "4005", "-i"]
    volumes:
      - .:/go/src/github.com/talento90/imgart
    links:
      - redis-db
      - mongo-db
    network_mode: bridge

  redis-db:
    image: redis:4-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./redis.conf:/config/redis.conf
    command: redis-server /config/redis.conf
    restart: always
    network_mode: bridge

  mongo-db:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    network_mode: bridge